[package]
name = "effing-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.42"
syn = { version = "1.0.98", features = ["full", "fold"] }
quote = "1.0.20"
